name: Ian Duncan
favicon: null
layout_spectrum: 0.25418
typography_spectrum: 0.8858
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cad3e2'
    - '#868f94'
    - '#0f131e'
    - '#646c6f'
    - '#3e4648'
  brandStrength: 0.75
  lightness: 0.8154061876703054
  saturation: 0.9168713327962905
  rhythmicContrast: 0.1949987318366766
purpose: []
